//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoffeeTime.Foot.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChampionshipTieRanking
    {
        public int Id { get; set; }
        public int ChampionshipId { get; set; }
        public int RankingId { get; set; }
        public int Rank { get; set; }
    
        public virtual Championship Championship { get; set; }
        public virtual TieRanking TieRanking { get; set; }
    }
}
