//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoffeeTime.Foot.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Championship
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Championship()
        {
            this.ChampionshipTieRanking = new HashSet<ChampionshipTieRanking>();
            this.Season = new HashSet<Season>();
        }
    
        public int Id { get; set; }
        public string Label { get; set; }
        public int TeamNumber { get; set; }
        public int WinPts { get; set; }
        public int DefeatPts { get; set; }
        public int TiePts { get; set; }
        public Nullable<int> PaysId { get; set; }
    
        public virtual Pays Pays { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChampionshipTieRanking> ChampionshipTieRanking { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Season> Season { get; set; }
    }
}
