//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoffeeTime.Foot.Core.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CoffeeTime_FootEntities : DbContext
    {
        public CoffeeTime_FootEntities()
            : base("name=CoffeeTime_FootEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Article> Articles { get; set; }
        public virtual DbSet<ArticleCategory> ArticleCategories { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Championship> Championships { get; set; }
        public virtual DbSet<ChampionshipTieRanking> ChampionshipTieRankings { get; set; }
        public virtual DbSet<Comment> Comments { get; set; }
        public virtual DbSet<Match> Matchs { get; set; }
        public virtual DbSet<Pays> Pays { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<Season> Seasons { get; set; }
        public virtual DbSet<SeasonTeam> SeasonTeams { get; set; }
        public virtual DbSet<Team> Teams { get; set; }
        public virtual DbSet<TieRanking> TieRankings { get; set; }
    }
}
